

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.88.224:1433;DatabaseName=TestDB
    username: test
    password: 1234

  server:
    port: 3000
